version: '3.8'

services:
  slurm:
    build:
      context: ../
      dockerfile: dev/Dockerfile.slurm
    container_name: lazyslurm_dev
    hostname: slurmctld
    ports:
      - "6817:6817"
      - "6818:6818" 
    volumes:
      - ./test_jobs:/home/slurm/jobs
      - ./test_data:/home/slurm/data
      - slurm_logs:/var/log/slurm
    environment:
      - CLUSTER_NAME=lazyslurm_dev
    stdin_open: true
    tty: true
    privileged: true

volumes:
  slurm_logs: